### ISSUE TITLE
Please provide a license.

### ISSUE THREAD

**Issue by shea-parkes** [milliman/SOA_PAF_Section_Newsletter_Catalogue#2]
Thanks for sharing this. Could you go ahead and please include an appropriate license with this repository?

**Comment by esburnsFA** [comment]
Thanks for the notes, Shea, I'm new to this!
If I use a similar license to that Matthias used in the KMeans repository, can you comment on whether that will suffice?

**Comment by shea-parkes** [comment]
An MIT license seems reasonable.  There are many viable options, it's just important to choose one of them.  Thanks for getting to these.  I'll go ahead and rename the repo and close out that last issue.
